#!/usr/bin/env ruby
require 'socket'
if ARGV.empty? 
  puts "#{__FILE__} host port"
  exit(1)
end
host = Addrinfo.tcp(ARGV[0],ARGV[1])
host.connect do |socket|
  socket.puts "NICK #{ARGV[2]}"
  socket.puts "USER guest tolmoon tolsun :Ronnie Reagan"
  socket.puts "JOIN #ram9"
  while rest = socket.gets
    puts rest
  end
end
